### PR TITLE
Added json development dependency

### PR DESCRIPTION
**Pull request by DariuszMusielak**
HI,

I have tried to use this gem and I have some problems on CircleCI. Basically, when I tried to setup db it says: `LoadError: cannot load such file -- JSON` from https://github.com/DariuszMusielak/alpr/blob/master/lib/alpr.rb#L4

I added `json` as a `development_dependency` and it works now.

### CODE REVIEW

**Comment by amonks** [comment]
Thank you Darius!

I don't use this gem anymore, and I can't devote a ton of time to maintenance.

It sounds like this change made it work better for you. I'll merge it.

It looks like travis was failing before, too, so I don't really mind that it still is in this branch.

**Comment by Divoolej** [comment]
Hi @amonks, would it be possible to release the latest version on RubyGems? That shouldn't be very time consuming and it would certainly be convenient for the people who use it. 🙏

**Comment by amonks** [comment]
It is unlikely that I will do this anytime soon.

If someone would like to take over stewardship of this repo, I'd be happy to transfer it and any relevant rubygems creds to that person.

**Comment by zjwhitehead** [comment]
@amonks are you still looking to hand this off? If so whats a good way to contact you?

**Comment by amonks** [comment]
@zjwhitehead sure! I'm definitely not gonna maintain this personally.

use the email address on my profile, and put `amonks/alpr` in the subject line.

**Comment by amonks** [comment]
I have transferred gem ownership to @zjwhitehead.
We are working on moving the repo also.

**Pull request merged**
